name: GPU Unit Tests

on: workflow_dispatch

env:
  IMAGE: alideeprec/deeprec-cicd:deeprec-dev-gpu-cibuild-py38-cu116-ubuntu20.04
  JOBNAME: deeprec-ci-gpu-${{ github.run_id }}
  PODNAME: deeprec-ci-gpu-${{ github.run_id }}-chief-0
  BAZEL_CACHE: ${{ secrets.BAZEL_CACHE }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PAI DLC
    steps:
    - name: Setup Environment
      uses: aliyun/ack-set-context@v1
      with:
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
        cluster-id: "${{ secrets.ACK_CLUSTER_ID }}"
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Pod
      timeout-minutes: 360
      run: |-
        helm install ${JOBNAME} cibuild/ --set image=${IMAGE} --set gpu=1
    - name: Upload Source
      if: ${{ always() }}
      run: |-
        cibuild/upload.sh ${PODNAME} ../cibuild
    - name: Unit Test
      if: ${{ always() }}
      run: |-
        kubectl exec -ti ${PODNAME} -- cibuild/gpu-ut.sh
    - name: Uninstall Pod
      if: ${{ always() }}
      run: |-
        helm uninstall ${JOBNAME}
